# Copyright (C) 2021 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Kibana Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-kibana
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-kibana
  template:
    metadata:
      labels:
        app: wazuh-kibana
      name: wazuh-kibana
    spec:
      volumes:
        - name: config
          configMap:
            name: kibana-conf
        - name: kibana-certs
          secret:
            secretName: kibana-certs
      containers:
        - name: wazuh-kibana
          image: 'whackers/kibana-k8s:latest'
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: config
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
              readOnly: false
            - name: kibana-certs
              mountPath: /usr/share/kibana/certs/cert.pem
              readOnly: true
              subPath: cert.pem
            - name: kibana-certs
              mountPath: /usr/share/kibana/certs/key.pem
              readOnly: true
              subPath: key.pem
            - name: kibana-certs
              mountPath: /usr/share/kibana/certs/root-ca.pem
              readOnly: true
              subPath: root-ca.pem
          ports:
            - containerPort: 5601
              name: kibana
          env:
            - name: ELASTICSEARCH_URL
              value: 'https://wazuh-elasticsearch-0.wazuh-elasticsearch:9200'
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elastic-cred
                  key: username
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-cred
                  key: password
            - name: KIBANA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kibana-cred
                  key: username
            - name: KIBANA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kibana-cred
                  key: password
            - name: SERVER_SSL_ENABLED
              value: "true"
            - name: SERVER_SSL_CERTIFICATE
              value: /usr/share/kibana/certs/cert.pem
            - name: SERVER_SSL_KEY
              value: /usr/share/kibana/certs/key.pem
            - name: WAZUH_API_URL
              value: https://wazuh-manager-master-0.wazuh-cluster
            - name: API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wazuh-api-cred
                  key: username
            - name: API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wazuh-api-cred
                  key: password
